### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by ndibgd** [adamlatchem/toolchest#2]
Thanks for sharing json-edit.  
I do get the error trying to save the following json file.
The error report is below.

{
        "apple": "value",
	"orange": 12,
	"banana": [1,2,3,"One","Two","Three","Fourth"],
	"grape": false,
	"strawberry": null,
	"carrot": [
		{
			"fourth": "value-two",
			"first": {
				"apple": "value1",
				"orange": "value2"
			},
			"second": "value",
			"third": "another"
		},
		{},
		["One","Two","Three"]
	],
	"pear": {
		"first": "value",
		"second": "another",
		"third": [1,2,3,"One","Two","Three"],
		"fourth": [
			{
				"first": "value",
				"second": "another"
			},
			{}
		]
	}
}

<traceback object at 0x000002BE07FAE488>
Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "json-edit.py", line 154, in cmd_save
    self.model.loads(self.tree_to_json())
  File "json-edit.py", line 261, in tree_to_json
    value = self.tree_to_json(key_id)
  File "json-edit.py", line 269, in tree_to_json
    inner += self.tree_to_json(key_id)
TypeError: can only concatenate str (not "int") to str

**Comment by adamlatchem** [comment]
Hi @ndibgd thank you for your feedback - it uncovered two issues with string concatenation of ints. Please pull the latest for the fix and let me know how you get on.
