### ISSUE TITLE
Delete key keyboard shortcut

### ISSUE THREAD

**Issue by mcarans** [adamlatchem/toolchest#7]
Thanks for a great tool! 

It would be great if the tool allowed the use of the del key to delete (in addition to the menu item). It would make it a quicker process.

**Comment by adamlatchem** [comment]
@mcarans please give the latest on master (ebdd61e48a4b7fa42a86a2e0a88bb74e5f226c7b) a go.

**Comment by mcarans** [comment]
Brilliant. It works well. Thanks a lot!
